apiVersion: 1

datasources:
  # Prometheus - Spring Boot 메트릭
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  # InfluxDB - k6 메트릭
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: imyme
      defaultBucket: k6
      tlsSkipVerify: true
    secureJsonData:
      token: imyme-local-token-2026
    editable: true